// Generated by CoffeeScript 1.6.3
/*
 Module dependencies.
*/


(function() {
  var app, docs_server_emulated, express, http, http_proxy, path, proxy, routes, server, user;

  http = require('http');

  http_proxy = require('http-proxy');

  express = require('express');

  routes = require('./routes');

  user = require('./routes/user');

  path = require('path');

  app = express();

  server = http.createServer(app);

  proxy = new http_proxy.RoutingProxy();

  app.set('port', process.env.PORT || 3000);

  app.set('views', __dirname + '/views');

  app.set('view engine', 'ejs');

  app.use(express.favicon());

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(require('stylus').middleware(__dirname + '/public'));

  app.use(express["static"](path.join(__dirname, 'public')));

  docs_server_emulated = function(req, res, callback) {
    return proxy.proxyRequest(req, res, {
      host: 'localhost',
      port: 9001
    });
  };

  app.use(express.vhost("docs.ipviope.tk", docs_server_emulated));

  if ('development' === app.get('env')) {
    app.use(express.errorHandler());
  }

  app.get('/', routes.index);

  app.get('/users', user.list);

  server.listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

}).call(this);
