// Generated by CoffeeScript 1.6.3
(function() {
  var avoid_sql_injection, build, db, mysql, options, query;

  mysql = require('mysql');

  options = {
    host: '127.0.0.1',
    database: 'ipviope',
    user: 'root',
    password: 'Yggdrasil/54.'
  };

  db = mysql.createConnection(options);

  db.connect();

  query = function(sqlQuery, params, callback) {
    query = build(sqlQuery, params);
    console.log(query);
    return db.query(query, function(err, rows, fields) {
      return callback(err, rows, fields);
    });
  };

  build = function(query, params) {
    var p, param, q, _i, _len;
    q = query;
    for (_i = 0, _len = params.length; _i < _len; _i++) {
      param = params[_i];
      p = avoid_sql_injection(param);
      q = q.replace("?", p);
    }
    return q;
  };

  avoid_sql_injection = function(str) {
    return str.replace(/[\0\x08\x09\x1a\n\r"'\\\%]/g, function(char) {
      switch (char) {
        case "\0":
          return "\\0";
        case "\x08":
          return "\\b";
        case "\x09":
          return "\\t";
        case "\x1a":
          return "\\z";
        case "\n":
          return "\\n";
        case "\r":
          return "\\r";
        case "\"":
        case "'":
        case "\\":
        case "%":
          return "\\" + char;
      }
    });
  };

  exports.query = query;

}).call(this);
