// Generated by CoffeeScript 1.6.3
/*

	Ce proxy est la racine du site

	Il permet de faire tourner tourner toutes les applis sur un même port ( 80 )
*/


(function() {
  var options, proxy, proxy_port;

  proxy_port = 80;

  options = {
    router: {
      "ipviope.tk": "localhost:3001",
      "docs.ipviope.tk": "localhost:9001",
      "aci-charlemagne.tk": "localhost:81"
    }
  };

  proxy = require('http-proxy').createServer(options);

  proxy.listen(proxy_port);

}).call(this);
