// Generated by CoffeeScript 1.6.3
(function() {
  var Users, init, io, start_ws;

  Users = require("../users/users");

  io = null;

  init = function(Socket_Instance) {
    io = Socket_Instance;
    return start_ws();
  };

  start_ws = function() {
    return io.of('/home').on("connection", function(socket) {
      socket.emit("message", "hello home!");
      return socket.on("get_users_list", function(no_data, callback) {
        return Users.get_users_list(function(data) {
          return callback(data);
        });
      });
    });
  };

  exports.init = init;

}).call(this);
