// Generated by CoffeeScript 1.6.3
(function() {
  var News, Users, init, io, request, start_ws;

  News = require("../news/news");

  Users = require("../users/users");

  request = require("request");

  io = null;

  init = function(Socket_Instance) {
    io = Socket_Instance;
    return start_ws();
  };

  start_ws = function() {
    return io.of('/home').on("connection", function(socket) {
      socket.emit("message", "hello home!");
      socket.on("get_news_list", function(no_data, callback) {
        return News.get_news_list(function(data) {
          return callback(data);
        });
      });
      socket.on("get_users_list", function(no_data, callback) {
        return Users.get_users_list(function(data) {
          return callback(data);
        });
      });
      return socket.on("random_pokemon", function(no_data, callback) {
        var base_url, url;
        base_url = "http://randompokemon.com/";
        url = "" + base_url + "random.php?n=1&ubers=true&nfe=true&natures=false&region=all&type=all&iesucks=1384359705075";
        return request(url, function(err, reponse, body) {
          var data, inf, sup, _ref;
          if (!err) {
            if ((200 <= (_ref = reponse.statusCode) && _ref < 300)) {
              data = body;
              inf = data.indexOf("src=");
              data = data.slice(inf + 5, +(data.length - 1) + 1 || 9e9);
              sup = data.indexOf('"');
              data = data.slice(0, +(sup - 1) + 1 || 9e9);
              return callback(base_url + data);
            }
          }
        });
      });
    });
  };

  exports.init = init;

}).call(this);
