// Generated by CoffeeScript 1.7.1

/*
 GET /calendar page.
 */


exports.calendar = function (req, res) {
    "use strict";
    if (!req.session || !req.session.connected) {
        res.redirect("/");
    } else {
        res.render('calendar');
    }
};


