// Generated by CoffeeScript 1.7.1

/*
 GET /chat page.
 */


exports.chat = function (req, res) {
    "use strict";
    var user, session;
    session = req.session;
    user = (session !== null ? session.user : undefined);
    if (!req.session || !req.session.connected) {
        res.redirect("/");
    } else {
        res.render('chat', {
            user: user
        });
    }
};


