// Generated by CoffeeScript 1.7.1

/*
 GET /easteregg page.
 */


exports.easteregg = function (req, res) {
    "use strict";
    if (!req.session || !req.session.connected) {
        res.redirect("/");
    } else {
        res.render('easter-egg');
    }

};

