// Generated by CoffeeScript 1.6.3
/*
 GET home page.
*/


(function() {
  exports.home = function(req, res) {
    var options;
    if (!req.session || !req.session.connected) {
      return res.redirect("/");
    } else {
      options = {
        title: "Welcome - IpVIOPE"
      };
      return res.render('home', options);
    }
  };

}).call(this);
