// Generated by CoffeeScript 1.7.1

/* 
Router
 */


exports.login = require("./login").login;

exports.home = require("./home").home;

exports.calendar = require("./calendar").calendar;

exports.chat = require("./chat").chat;

exports.account = require("./account").account;
exports.accountUpdate = require("./account").accountUpdate;

exports.easteregg = require("./easteregg").easteregg;


