// Generated by CoffeeScript 1.7.1

/*
    Parametrage de L'ORM
 */


var ORM, Sequelize, config, e;

Sequelize = require('sequelize');

config = require('../Database_config').config;

if (config !== null) {
    try {
        ORM = new Sequelize(config.database, config.user, config.password, {
            dialect: config.dialect,
            host: config.host,
            port: config.port
        });
        ORM.authenticate().complete(function (err) {
            "use strict";
            if (err !== null) {
                console.log('Unable to connect to the database:', err);
            } else {
                console.log('Connection to Database has been established successfully.');
            }
        });
    } catch (error) {
        console.log("Erreur de connexion à la BDD : " + error);
    }
}

exports.db = ORM;

