// Generated by CoffeeScript 1.7.1

/*
    
 Défini une exception générique
 */


var Exception;

Exception = (function () {

    "use strict";

    var code, message;

    message = "";

    code = null;

    function Exception(string, code_d_erreur) {
        if (string !== null) {
            message = string;
        }
        if (code_d_erreur !== null) {
            code = code_d_erreur;
        }
    }

    return Exception;

})();

exports.Exception = Exception;
