// Generated by CoffeeScript 1.7.1

var Exception, Rooms, db, liste, message, i;

db = require('../models');

Exception = require('./Exception').Exception;


/*

    Controlleur gérant les Rooms
 */

Rooms = (function () {

    "use strict";
    
    function Rooms() {}

    Rooms.addMessage = function (room_name, message_a_ajouter) {
        db.Room.findOrCreate({
            name: room_name
        }).success(function (room) {
            db.User.find(message_a_ajouter.user.id).success(function (user) {

                db.Message.create(message_a_ajouter).success(function (message) {
                    message.setRoom(room).success(function () {
                        message.setUser(user);
                    });
                });
            });
        });
    };


    Rooms.getMessages = function (name_param, callback) {
        var query;

        query = db.Room.find({
            where: {
                name: name_param
            },
            include: [
                {
                    model: db.Message,
                    include: [
                        db.User
                    ]
                }
            ]
        });
        query.success(function (room) {
            if (room) {

                liste = room.messages;
                for (i = 0; i < liste.length; i += 1) {
                    message = liste[i];
                    message.for = room.name;
                    message.date = message.createdAt;
                    liste[i] = message;
                }
                callback(null, liste);

            }
        });
        query.error(function (err) {
            console.log("Rooms@find_by_title: " + err);
            callback(err, null);
        });
        
    };

    return Rooms;

})();

exports.Rooms = Rooms;