// Generated by CoffeeScript 1.6.3
(function() {
  var DB, connect;

  DB = require("../../connect_database");

  connect = function(request, response) {
    var e, next, params, password, query, username;
    username = request.param("username");
    password = request.param("password");
    console.log("Connection de : " + username + ' | ' + password);
    query = "SELECT *\n FROM users\n WHERE username= '?'\n AND password = '?'";
    params = [username, password];
    next = function(erreur, lignes, champs) {
      var message, retour;
      message = "";
      if (erreur) {
        console.warn(erreur);
        message = "error";
      } else {
        if (lignes.length !== 1) {
          message = "user_not_exist";
        } else {
          message = "ok";
          /*
          				ENREGISTREMENT DANS LA SESSION
          */

          request.session.connected = true;
        }
      }
      retour = {
        'message': message
      };
      retour = JSON.stringify(retour);
      console.log(retour);
      return response.end(retour);
    };
    try {
      return DB.query(query, params, next);
    } catch (_error) {
      e = _error;
      return console.warn(e);
    }
  };

  exports.connect = connect;

}).call(this);
