// Generated by CoffeeScript 1.6.3
(function() {
  var DB, connect, disconnect, get_users_list;

  DB = require("../../connect_database");

  connect = function(request, response) {
    var e, next, params, password, query, username;
    username = request.param("username");
    password = request.param("password");
    console.log("Connection de : " + username + ' | ' + password);
    query = "SELECT *\n FROM users\n WHERE username= '?'\n AND password = '?'";
    params = [username, password];
    next = function(erreur, lignes, champs) {
      var message, retour;
      message = "";
      if (erreur) {
        console.warn(erreur);
        message = "error";
      } else {
        if (lignes.length !== 1) {
          message = "user_not_exist";
        } else {
          message = "ok";
          /*
          				ENREGISTREMENT DANS LA SESSION
          */

          request.session.connected = true;
          request.session.username = lignes[0].username;
          request.session.user_id = lignes[0].id;
        }
      }
      retour = {
        'message': message
      };
      retour = JSON.stringify(retour);
      console.log(retour);
      return response.end(retour);
    };
    try {
      return DB.query(query, params, next);
    } catch (_error) {
      e = _error;
      return console.warn(e);
    }
  };

  get_users_list = function(callback) {
    var e, next, query;
    query = "SELECT username, nom , prenom, country\n FROM users;\n ";
    next = function(erreur, lignes, champs) {
      if (erreur) {
        return console.warn(erreur);
      } else {
        return callback(lignes);
      }
    };
    try {
      return DB.query(query, [], next);
    } catch (_error) {
      e = _error;
      return console.warn(e);
    }
  };

  disconnect = function(request, response) {
    if (request.session && request.session.connected) {
      request.session.destroy();
    }
    return response.redirect("/");
  };

  /*
  get_settings_list = (callback) ->
  	#get params
  	usersession = request.session.username
  
  	#create query
  	query = """
  				SELECT username, nom, prenom
  				FROM users
  				WHERE username= '?'
  			"""
  	params = [
  		usersession
  	]
  
  	# treat query 
  	next = ( erreur, lignes, champs)->
  		
  		if erreur
  			console.warn erreur
  		else
  			callback (lignes)
  			Console.log (lignes) 
  
  	# execute query
  	try
  		DB.query query, params , next
  	catch e
  		console.warn e
  */


  exports.connect = connect;

  exports.get_users_list = get_users_list;

  exports.disconnect = disconnect;

  /*
  exports.get_settings_list = get_settings_list
  */


}).call(this);
