// Generated by CoffeeScript 1.6.3
(function() {
  var DB, get_news_list;

  //DB = require("../../connect_database");

  get_news_list = function(callback) {
    var next, params, sql;
    sql = "SELECT *\nFROM news\nORDER BY id DESC";
    params = [];
    next = function(err, rows, fields) {
      if (err) {
        return console.warn(err);
      } else {
        return callback(rows);
      }
    };
    return DB.query(sql, params, next);
  };

  exports.get_news_list = get_news_list;

}).call(this);
