// Generated by CoffeeScript 1.7.1

/*
    Défini l'entitée Country
 */


module.exports = function (sequelize, DataTypes) {
    "use strict";
    var Country;
    Country = sequelize.define('Country', {
        id: {
            type: DataTypes.INTEGER.UNSIGNED,
            autoIncrement: true,
            primaryKey: true
        },
        name: {
            type: DataTypes.STRING,
            allowNull: false,
            unique: true
        }
    }, {
        classMethods: {
            associate: function (models) {
                Country.hasOne(models.Image);
                Country.hasMany(models.User);
                Country.hasMany(models.Project);
            }
        }
    });
    return Country;
};


